#!/usr/bin/env python3
"""
Synthesize sheet summaries into a final Business Requirements Document.

Usage:
    python brd_synthesize.py <summaries_dir> <output_file> [--api-key KEY]

Output:
    final_brd.md - Complete Business Requirements Document
"""

import sys
import os
import re
import glob
import argparse
from pathlib import Path
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

SCRIPT_DIR = Path(__file__).parent


def load_prompt(filepath: Path) -> str:
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()


def load_all_summaries(summaries_dir: str) -> dict:
    """Load all markdown summaries from directory."""
    summaries = {}
    md_files = sorted(glob.glob(os.path.join(summaries_dir, "*.md")))
    
    for md_path in md_files:
        if md_path.endswith("_index.md"):
            continue
        sheet_name = Path(md_path).stem
        try:
            with open(md_path, 'r', encoding='utf-8') as f:
                summaries[sheet_name] = f.read()
        except Exception as e:
            print(f"Warning: Could not read {md_path}: {e}")
    
    return summaries


def combine_summaries(summaries: dict) -> str:
    """Combine all summaries into a single text block."""
    parts = []
    for sheet_name in sorted(summaries.keys()):
        parts.append(f"### Sheet ID: {sheet_name}\n\n{summaries[sheet_name]}\n")
        parts.append("-" * 80 + "\n")
    return "\n".join(parts)


def extract_valid_image_filenames(summaries: dict) -> set:
    """Extract valid image filenames from Section 10 of all summaries."""
    valid = set()
    section_pattern = r'## 10\. Danh sách hình ảnh.*?(?=\n## |\n---|\Z)'
    token_pattern = r'<<IMAGE:([^>]+)>>'
    
    for summary in summaries.values():
        match = re.search(section_pattern, summary, re.DOTALL)
        if match:
            for m in re.finditer(token_pattern, match.group(0)):
                valid.add(m.group(1))
    return valid


def convert_image_tokens(brd_content: str, valid_filenames: set):
    """Convert <<IMAGE:filename>> tokens to markdown image syntax."""
    stats = {'converted': 0, 'invalid_removed': 0, 'invalid_list': []}
    
    def replace_token(match):
        filename = match.group(1)
        if filename in valid_filenames:
            stats['converted'] += 1
            desc = filename.replace('_', '.').replace('.png', '').replace('.jpg', '')
            parts = desc.split('.')
            desc = f"{'.'.join(parts[:-2])} {parts[-2]}" if len(parts) > 2 else desc
            return f"![{desc}](images/{filename})"
        else:
            stats['invalid_removed'] += 1
            stats['invalid_list'].append(filename)
            return f"<!-- Invalid image token removed: {filename} -->"
    
    return re.sub(r'<<IMAGE:([^>]+)>>', replace_token, brd_content), stats


def append_missing_images(brd_content: str, missing: list) -> str:
    """Append missing images to BRD as appendix."""
    if not missing:
        return brd_content
    
    appendix = "\n\n---\n\n## Phụ lục: Hình ảnh bổ sung\n\n"
    for filename in missing:
        desc = filename.replace('_', ' ').replace('.png', '').replace('.jpg', '')
        appendix += f"![{desc}](images/{filename})\n\n"
    
    if "\n---\n\n*Generated by Claude" in brd_content:
        parts = brd_content.rsplit("\n---\n\n*Generated by Claude", 1)
        return parts[0] + appendix + "\n---\n\n*Generated by Claude" + parts[1]
    return brd_content + appendix


def synthesize_brd(client: Anthropic, summaries: dict, max_tokens: int = 32000) -> str:
    """Synthesize all summaries into a final BRD using Claude."""
    if not summaries:
        return "# Error\n\nNo summaries provided for synthesis."
    
    system_prompt = load_prompt(SCRIPT_DIR / "prompts" / "system_prompt.md")
    user_template = load_prompt(SCRIPT_DIR / "prompts" / "user_prompt.md")
    
    summaries_text = combine_summaries(summaries)
    user_prompt = user_template.format(num_sheets=len(summaries), summaries=summaries_text)
    
    print(f"Synthesizing {len(summaries)} sheets ({len(summaries_text):,} chars)...")
    print("Generating BRD (streaming)...", end="", flush=True)
    
    try:
        brd_content = ""
        with client.messages.stream(
            model="claude-opus-4-5",
            max_tokens=max_tokens,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}]
        ) as stream:
            for text in stream.text_stream:
                brd_content += text
                print(".", end="", flush=True)
        print(" Done!")
        
        # Process images
        valid_filenames = extract_valid_image_filenames(summaries)
        brd_tokens = set(re.findall(r'<<IMAGE:([^>]+)>>', brd_content))
        missing = list(valid_filenames - brd_tokens)
        
        brd_content, stats = convert_image_tokens(brd_content, valid_filenames)
        print(f"Images: {stats['converted']} converted, {stats['invalid_removed']} invalid, {len(missing)} missing")
        
        if missing:
            brd_content = append_missing_images(brd_content, missing)
        
        # Add metadata
        image_count = len(re.findall(r'!\[[^\]]*\]\(images/[^)]+\)', brd_content))
        brd_content += f"\n\n---\n\n*Generated from {len(summaries)} sheets | Images: {image_count}*\n"
        
        return brd_content
        
    except Exception as e:
        return f"# Error Generating BRD\n\n{e}"


def main():
    parser = argparse.ArgumentParser(description="Synthesize sheet summaries into final BRD")
    parser.add_argument('summaries_dir', help='Directory with summary markdown files')
    parser.add_argument('output_file', help='Output BRD markdown file')
    parser.add_argument('--api-key', help='Anthropic API key')
    parser.add_argument('--max-tokens', type=int, default=32000, help='Max tokens (default: 32000)')
    args = parser.parse_args()
    
    if not os.path.exists(args.summaries_dir):
        sys.exit(f"Error: Directory not found: {args.summaries_dir}")
    
    api_key = args.api_key or os.environ.get('ANTHROPIC_API_KEY')
    if not api_key:
        sys.exit("Error: No API key. Set ANTHROPIC_API_KEY or use --api-key")
    
    summaries = load_all_summaries(args.summaries_dir)
    if not summaries:
        sys.exit("Error: No summaries found")
    
    print(f"Loaded {len(summaries)} summaries")
    
    client = Anthropic(api_key=api_key)
    brd_content = synthesize_brd(client, summaries, args.max_tokens)
    
    output_dir = os.path.dirname(args.output_file)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    
    with open(args.output_file, 'w', encoding='utf-8') as f:
        f.write(brd_content)
    
    print(f"✅ Done: {args.output_file} ({os.path.getsize(args.output_file):,} bytes)")


if __name__ == "__main__":
    main()